language: java
jdk:
  - openjdk8
  - openjdk11
addons:
cache:
  directories:
    - $HOME/.m2
install:
  - export CODACY_COVERAGE_REPORTER_VERSION=6.0.0
  - export CODACY_PROJECT_TOKEN=7b7633aa2c1f4477ade4b81986fbe084
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/${CODACY_COVERAGE_REPORTER_VERSION}/codacy-coverage-reporter-${CODACY_COVERAGE_REPORTER_VERSION}-assembly.jar
script:
  - mvn clean install -Dapp.log.level.test=info
after_script:
  - mvn jacoco:report -pl spring-test-terasoluna-gfw
  - java -jar codacy-coverage-reporter-${CODACY_COVERAGE_REPORTER_VERSION}-assembly.jar report -l Java -r spring-test-terasoluna-gfw/target/site/jacoco/jacoco.xml
